name: group9_airbnb_environment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - folium=0.16.0
  - ipykernel=6.29.3
  - jupyterlab=4.1.5
  - matplotlib=3.8.3
  - nb_conda_kernels
  - nbconvert=7.16.2
  - numpy=1.26.4
  - pandas=2.2.1
  - pip>=23.2.1
  - plotly=5.19.0
  - requests=2.31.0
  - scikit-learn=1.4.1.post1
  - scipy=1.12.0
  - seaborn=0.13.2
  - tabulate=0.9.0
  - iniconfig=2.0.0
  - pluggy=1.4.0
  - pytest=8.1.1